### ISSUE TITLE
422 status code required

### ISSUE THREAD

**Issue by appkr** [shrikeh/teapot#38]
Hi?

I've started using this package from today, and find out that '422 Unprocessable Entity' status is not available. Since I don't understand how the code is working under the hood at the moment, I hope you add this. If I happen to understand things and have a chance to add it, I will propose a PR.

Thanks.

**Comment by localheinz** [comment]
@appkr 

How about https://github.com/shrikeh/teapot/blob/2a31a80746bca2a5bece0436ba333bcf3f67aaf0/src/StatusCode/RFC/RFC4918.php#L74?

**Comment by appkr** [comment]
@localheinz Thanks for the answer. Hope I can use `\Teapot\StatusCode::UNPROCESSABLE_ENTITY` instead of `\Teapot\StatusCode\RFC\RFC4918::UNPROCESSABLE_ENTITY`. I think I will have to implement my `StatusCode` class that combines everything. That's the right way of use, you intended to, right? Thanks.

**Comment by localheinz** [comment]
@appkr 

You could use

```php
use Teapot\StatusCode;

var_dump(StatusCode\All:: UNPROCESSABLE_ENTITY);
```

:+1:

**Comment by appkr** [comment]
Nice and clean! It would be better if it is included in readme. Thanks \^^/

**Comment by bartboy011** [comment]
@localheinz I'm attempting to use your suggestion above but am running into a fatal error:

http://screen.ac/3I1P2s3a0L1y

I ran a search in GitHub and it looks like the constant `UPGRADE_REQUIRED` is set on both `RFC2817` and `RFC7231`. My assumption then is that `All` is inheriting from both, albeit through an extended inheritance chain. Any thoughts?

**Comment by shrikeh** [comment]
@bartboy011 I can look into that right now.

**Comment by shrikeh** [comment]
I am going to pull RFC2817  from being included in ALL

**Comment by bartboy011** [comment]
Sounds good, thank you!
