### ISSUE TITLE
Support psr/http-message 2.0

### ISSUE THREAD

**Issue by theodorejb** [shrikeh/teapot#54]
The current requirement of only psr/http-message 1.0 prevents using this library with any project which depends on psr/http-message 2.0.

Can the dependency requirement be updated to support psr/http-message 2.0? I'm happy to open a merge request to do this.

**Comment by theodorejb** [comment]
@shrikeh Can a new tag be pushed with this fix? It might need to be v3.0.0 since PHP 8.0+ is now required.

**Comment by shrikeh** [comment]
Sure, I can do this in half an hour
  
On Sun, Oct 6, 2024 at 03:43, Theodore Brown ***@***.***&gt; wrote:   @shrikeh Can a new tag be pushed with this fix? It might need to be v3.0.0 since PHP 8.0+ is now required. —

**Comment by theodorejb** [comment]
> Sure, I can do this in half an hour

@shrikeh Thank you, I would really appreciate it!
